config/routes.rb
Rails.application.routes.draw do
  
  resources :places  do
    resources :appointments
  end

  
  resources :projects do
    member do
      patch 'star'
      put 'star'
    end
  end
  resources :categories
  resources :groups do
    member do
      patch 'star'
      put 'star'
    end
  end
#  resources :comments
  resources :posts do
  	resources :comments 
  end
  resources :relationships, only: [:create, :destroy]
   devise_for :users 
  resources :users do
  	member do
  		get :following,:followers
  	end
  end

  get '/home' => 'pages#home' # override default routes.
   

  get '/user/:id' => 'pages#profile'
  get '/explore' => 'pages#explore'
  get '/index' => 'pages#index'
  root :to =>'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :appointments
  belongs_to :user
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  LIMITED_GROUPS_NUM =10
  # GET /groups
  # GET /groups.json
  def index
      @groups = Group.all      

    if params[:page]
      @page= params[:page].to_i
    else 
      @page = 1
    end

=begin    
    @groups=[]
    (1...100).each do |index|
      group ={

        id: index,
        price: 10,
      }
      @groups << group
    end
=end


#    @groups = group.all
      @first_page =(@groups.count==0)? 0:1
    @last_page=(@groups.count / LIMITED_GROUPS_NUM)+1

    @groups = @groups.offset((@page-1) * LIMITED_GROUPS_NUM).limit(LIMITED_GROUPS_NUM)

  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @appointments = Appointment.where("group_id = ?" ,params[:id])
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.user = current_user
    @group.attend_num =0
    respond_to do |format|
      if @group.save
        current_user.create_action( :like , target: @group)
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def star
    @user = User.find(current_user.id)
    if @user.like_group?(params[:id]) == false
       @user.like_group(params[:id])
       @favorite_exists = true
       respond_to do |format|
          format.html { redirect_to groups_url,   notice: 'group was successfully liked.' }
          format.json { head :no_content }
       end
    else
       @user.unlike_group(params[:id])
    #  @group.likes_count.save(touch: false)
       @favorite_exists = false
       respond_to do |format|
          format.html { redirect_to groups_url,  notice: 'group was successfully unliked.' }
          format.json { head :no_content }
       end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description,:attend_num)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<h1 class="h3 mb-3 font-weight-normal">Please fill in your details</h1>

<%= form_with(model: group, local: true) do |form| %>
      <% if group.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>
          <ul>
          <% group.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <label for="" class="col-md-12 control-label">Name</label>
        <%= form.text_field :name ,:class =>"form-control" ,:placeholder => "Groupname" %>
      </div>

      <div class="form-group">
        <label for="" class="col-md-12 control-label">Content</label>
        <%= form.text_area :description, :rows => "4" ,:class=> "col-md-12 form-control" , :placeholder => "Description"%>
      </div>

      <div class="actions">
        <%= form.submit "Register" ,  :class => "btn btn-lg btn-primary btn-block" %>
      </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>
<div class="container">
<div class="row">
      <div class="col-md-9">
          <table>
            <tbody>
              <% @groups.each do |group| %>
                <div class="row">
                  <div class ="col-md-12">
                    <div class="card flex-md-row mb-4 box-shadow h-md-250">
                      <div class="card-body d-flex flex-column align-items-start">
                        <h3 class="mb-0">
                          <%= link_to group.name, group_path(group), :class=>"text-black" if group%> 
                        </h3>
                        <div class="mb-1 text-muted">Established:<%= time_ago_in_words(group.created_at) %> ago</div>
                        <p class="card-text mb-auto"><%= truncate(strip_tags(group.description),length: 80) if group.description%></p>
                        
                          <div class="mb-1 text-muted">Member count: </div><%= group.reload.likes_count %>
                          
                      </div>
                        <% if current_user.id == group.user.id %>
                           <%= button_to("You are the founder" , group_path(group)  ,method: :get , :class => "btn  btn-info" ) %> 
                        <% elsif current_user.like_group?(group) ==false %>
                         <%= button_to("Join the group" ,star_group_path(group)  ,method: :patch , :class => "btn btn-outline-success" ) %> 
                         <% else %>
                          <%= button_to( "Exit the group" , star_group_path(group)  , method: :patch , :class => "btn btn-outline-warning"  )%> 
                          <%end %>

                    </div>
                </div>
              </div>
           
                <% end %>
            </tbody>
          </table>
      </div>
        <div class="col-md-3">
            <div class="list-group">
              <%= link_to "All Groups", groups_url , :class =>"list-group-item list-group-item-action" %>
            </div>
          </div>
</div>

<nav aria-label="Page navigation example">
  <ul class="pagination">
    <% if @page > @first_page %>
      <li class="page-item">
        <%= link_to groups_path(page: ( @page -1)) ,:class => "page-link" do%>
        <span aria-hidden="true">previous</span>
        <% end %>
      </li>
    <% end %>

    <% (@first_page..@last_page).each do |page_number| %>
      <li><%= link_to page_number , groups_path(page: page_number,category: params[:category]),:class => "page-link" %></li>
    <% end %>

    <% if @page < @last_page %>
    <li class="page-item">
      <%= link_to groups_path(page: ( @page +1),category: params[:category] ),:class => "page-link" do%>
      <span aria-hidden="true">next</span>
      <% end %>
    </li>
    <% end %>
  </ul>
</nav>


<br>
</div>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>
<div class= "jumbotron">
  <div class="row">
      <div class ="col-md-4">
        <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1544159373240&di=4f814950749b391f15338061a714ef21&imgtype=0&src=http%3A%2F%2Fcdn2.ettoday.net%2Fimages%2F1975%2Fd1975857.jpg" class="rounded-img" height="100%" width="100%"></img>
      </div>
      <div class ="col-md-8">
        <div class="row">  
              <strong>Name: <br>  <%= @group.name %></strong>
        </div>
        <br>
        <br>
        <div class="row">
           Description: <br> <%= @group.description %>
        </div>
        <br>
        <br>
        <div class="row">
          Founder: <br>  <%= @group.user.username %> 
        </div>
        <br>
        <br>
        <div class="row">
          Member count:  <br>  <%= @group.likes_count %> 
        </div>
      </div>
  </div>
</div>


<%  @appointments.each do |f| %>
  <div class ="row">
  <div class="col-sm-1">
        <img src="/avatar.png" class="rounded-img" height="35px" width="35px"></img>
    </div>
  <div class="col-sm-11">
    <div class="card bg-light card-body">
      <%= link_to f.place.name , place_appointments_url(place_id: f.place_id) ,method: :get %>   appoint_time: <%= f.app_date %>  
    </div>
  </div>
</div>
<hr style="filter: alpha(opacity=100,finishopacity=0,style=1)" width="80%" color='#987cb9' size=3>
<%end %>

<% if is_admin or is_belonger(@group.user.id) %>
  <%= link_to 'Edit', edit_group_path(@group) %> |
  <%= link_to 'Back', groups_path %> | 
  <%= link_to 'Destroy',  @group , method: :delete %>
<% end %>