config/routes.rb
Rails.application.routes.draw do
  
  resources :places  do
    resources :appointments
  end

  
  resources :projects do
    member do
      patch 'star'
      put 'star'
    end
  end
  resources :categories
  resources :groups do
    member do
      patch 'star'
      put 'star'
    end
  end
#  resources :comments
  resources :posts do
  	resources :comments 
  end
  resources :relationships, only: [:create, :destroy]
   devise_for :users 
  resources :users do
  	member do
  		get :following,:followers
  	end
  end

  get '/home' => 'pages#home' # override default routes.
   

  get '/user/:id' => 'pages#profile'
  get '/explore' => 'pages#explore'
  get '/index' => 'pages#index'
  root :to =>'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  LIMITED_projectS_NUM =10
  # GET /projects
  # GET /projects.json
  def index
    if !params[:category].blank?
      @projects = Project.where(["category_id = ? ", params[:category]])
    else
      @projects = Project.all      
    end

    if params[:page]
      @page= params[:page].to_i
    else 
      @page = 1
    end

=begin    
    @projects=[]
    (1...100).each do |index|
      project ={

        id: index,
        price: 10,
      }
      @projects << project
    end
=end


#    @projects = project.all
      @first_page =(@projects.count==0)? 0:1
    @last_page=(@projects.count / LIMITED_projectS_NUM)+1

    @projects = @projects.offset((@page-1) * LIMITED_projectS_NUM).limit(LIMITED_projectS_NUM)

  end

  # GET /projects/1
  # GET /projects/1.json
  def show


    @users = @project.like_by_users
    
    
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user

    respond_to do |format|
      if @project.save
        current_user.create_action( :like , target: @project)
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def star
    @user = User.find(current_user.id)
  

    if @user.like_project?(params[:id]) == false
       @user.like_project(params[:id])
       @favorite_exists = true
       respond_to do |format|
          format.html { redirect_to projects_url,   notice: 'Project was successfully liked.' }
          format.json { head :no_content }
       end
    else
       @user.unlike_project(params[:id])
    #  @project.likes_count.save(touch: false)
       @favorite_exists = false
       respond_to do |format|
          format.html { redirect_to projects_url,  notice: 'Project was successfully unliked.' }
          format.json { head :no_content }
       end
    end

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :id ,:category_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="form-select" >
    <%= form.collection_select(:category_id, Category.all, :id , :name, class: "form-control" )  %>
   </div>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description , class: "form-control", rows: "10"%>
  </div>

  <div class="form-group">
    <%= form.submit "Create" ,:class => "btn btn-primary btn-lg"%>
  </div>

<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice">
  <%= notice %>
</p>
<!--
<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User</th>
      <th>Follows count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.user.username %></td>
        <td><%= project.reload.likes_count %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
-->

<div class="container">

<div class="row">
      <div class="col-md-9">
          <table>
            <tbody>
              <% @projects.each do |project| %>
                <div class="row">
                  <div class ="col-md-12">
                    <div class="card flex-md-row mb-4 box-shadow h-md-250">
                      <div class="card-body d-flex flex-column align-items-start">
                        <h3 class="mb-0">
                          <%= link_to project.name, project_path(project), :class=>"text-black" if project%> 
                        </h3>
                        <div class="mb-1 text-muted">Nov 12</div>
                        <p class="card-text mb-auto"><%= truncate(strip_tags(project.description),length: 80) if project.description%></p>
                        
                          <div class="mb-1 text-muted">Member count: </div><%= project.reload.likes_count %>
                          
                      </div>
                        <% if current_user.like_project?(project) ==false %>
                         <%= button_to("Join the project" ,star_project_path(project)  ,method: :patch , :class => "btn btn-outline-success" ) %> 
                         <% else %>
                          <%= button_to( "Exit the project" , star_project_path(project)  , method: :patch , :class => "btn btn-outline-warning"  )%> 
                          <%end %>

                    </div>
                </div>
              </div>
           
                <% end %>
            </tbody>
          </table>
      </div>
        <div class="col-md-3">
            <div class="list-group">
              <%= link_to "All items", projects_url , :class =>"list-group-item list-group-item-action" %>
              <div class="list-group-item font-weight">
                <h4>Category</h4>
              </div>
                <% Category.all.each do |cate| %>

               <%= link_to cate.name, projects_url(category: cate.id) ,:class=> "list-group-item list-group-item-action" %>
               <% end %>

            </div>
          </div>
</div>

<nav aria-label="Page navigation example">
  <ul class="pagination">
    <% if @page > @first_page %>
      <li class="page-item">
        <%= link_to projects_path(page: ( @page -1)) ,:class => "page-link" do%>
        <span aria-hidden="true">previous</span>
        <% end %>
      </li>
    <% end %>

    <% (@first_page..@last_page).each do |page_number| %>
      <li><%= link_to page_number , projects_path(page: page_number,category: params[:category]),:class => "page-link" %></li>
    <% end %>

    <% if @page < @last_page %>
    <li class="page-item">
      <%= link_to projects_path(page: ( @page +1),category: params[:category] ),:class => "page-link" do%>
      <span aria-hidden="true">next</span>
      <% end %>
    </li>
    <% end %>
  </ul>
</nav>

<%= button_to 'New project', new_project_path ,method: :get , :class => "btn btn-outline-success" %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice">
	<%= notice %>
</p>
<div class= "jumbotron">
  <div class="row">
      <div class ="col-md-4">
        <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1544159373240&di=4f814950749b391f15338061a714ef21&imgtype=0&src=http%3A%2F%2Fcdn2.ettoday.net%2Fimages%2F1975%2Fd1975857.jpg" class="rounded-img" height="100%" width="100%"></img>
      </div>
      <div class ="col-md-8">
        <div class="row">  
              <strong>Name: <br>  <%= @project.name %></strong>
        </div>
        <br>
        <br>
        <div class="row">
           Description: <br> <%= @project.description %>
        </div>
        <br>
        <br>
        <div class="row">
          Founder: <br>  <%= @project.user.username %> 
        </div>
        <br>
        <br>
        <div class="row">
          Member count:  <br>  <%= @project.likes_count %> 
        </div>
      </div>
  </div>
</div>

<hr style="filter: alpha(opacity=100,finishopacity=0,style=1)" width="80%" color='#987cb9' size=3>


<%  @users.each do |f| %>
	<div class ="row">
  <div class="col-sm-1">
        <img src="/avatar.png" class="rounded-img" height="35px" width="35px"></img>
    </div>
  <div class="col-sm-11">
  	<div class="card bg-light card-body">
			<%= f.username %> Join the project 
		</div>
	</div>
</div>
<hr style="filter: alpha(opacity=100,finishopacity=0,style=1)" width="80%" color='#987cb9' size=3>
<%end %>


<%=  button_to  star_text, star_project_path(@project), method: :patch, :class=>"btn btn-success" , id:'star_link' ,remote: true %>
<% if is_admin or is_belonger(@project.user.id)  %>
  <%= link_to 'Edit', edit_project_path(@project) %> |
<%end %>
<%= link_to 'Back', projects_url %>

app/views/projects/star.js.erb
$('#star_link' ).text("<%= star_text %>");