config/routes.rb
Rails.application.routes.draw do
  
  resources :places  do
    resources :appointments
  end

  
  resources :projects do
    member do
      patch 'star'
      put 'star'
    end
  end
  resources :categories
  resources :groups do
    member do
      patch 'star'
      put 'star'
    end
  end
#  resources :comments
  resources :posts do
  	resources :comments 
  end
  resources :relationships, only: [:create, :destroy]
   devise_for :users 
  resources :users do
  	member do
  		get :following,:followers
  	end
  end

  get '/home' => 'pages#home' # override default routes.
   

  get '/user/:id' => 'pages#profile'
  get '/explore' => 'pages#explore'
  get '/index' => 'pages#index'
  root :to =>'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name ,uniqueness: :true
	has_many :projects , :dependent => :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

       <div class="form-group">
        <label for="" class="col-md-12 control-label">Name</label>
        <%= form.text_field :name ,:class =>"form-control" ,:placeholder => "Category name" %>
      </div>

      <div class="actions">
        <%= form.submit "Add" ,  :class => "btn btn-lg btn-primary btn-block" %>
      </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>
    <% @categories.each do |category| %>
      <div class="jumbotron">
        <div class="row">
          <div class="col-md-2">
            <strong>Category:  </strong><br>
            <h3><%= link_to category.name, projects_path(category: category ) %> </h3>
          </div>
          <div class="col-md-2"><strong>Counts</strong><br><%= category.projects.count %></div>
            
        
          <div class="col-md-4">
              <% category.projects.limit(3).each do |topic| %>
                <div class="row">
                  <%= link_to topic.name, project_path(topic) %>
                  <%= time_tag topic.created_at %>
                </div>
              <% end %>
          </div>
          <div class="col-md-4">
            <div class= "row">
              <% if is_admin %>
              <center>
                <div class="col-md-12">
                <%= button_to '  Edit ',   edit_category_path(category) ,method: :get ,:class =>"btn btn-lg btn-info" %>
                </div>
                <div class="col-md-12">
                <%= button_to   'delete'  , category, method: :delete,:class =>"btn btn-lg btn-outline-warning", data: { confirm: 'Are you sure?' } %>
                </div>
                </center>
              <% end %>
          </div>
        </div>
      </div>
    </div>
    <% end %>



<% if is_admin  %>

  <%= link_to 'New Category', new_category_path %>
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>