config/routes.rb
Rails.application.routes.draw do
  
  resources :places  do
    resources :appointments
  end

  
  resources :projects do
    member do
      patch 'star'
      put 'star'
    end
  end
  resources :categories
  resources :groups do
    member do
      patch 'star'
      put 'star'
    end
  end
#  resources :comments
  resources :posts do
  	resources :comments 
  end
  resources :relationships, only: [:create, :destroy]
   devise_for :users 
  resources :users do
  	member do
  		get :following,:followers
  	end
  end

  get '/home' => 'pages#home' # override default routes.
   

  get '/user/:id' => 'pages#profile'
  get '/explore' => 'pages#explore'
  get '/index' => 'pages#index'
  root :to =>'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord

  validates :app_date, uniqueness: { scope: :place_id  , message: "already appointed! Please retry ." }

  belongs_to :place
  belongs_to :group
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name ,uniqueness: :true
	has_many :projects , :dependent => :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :appointments
  belongs_to :user
end

app/models/place.rb
class Place < ApplicationRecord
	validates :name ,presence: :true,uniqueness: :true
	has_many :appointments , dependent: :destroy
	
end

app/models/post.rb
class Post < ApplicationRecord
	validates_presence_of  :body
	validates :body , presence: true ,length: {maximum: 140}
	default_scope -> { order(created_at: :desc) }
	has_many :comments , :dependent => :destroy
    belongs_to :user

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts, dependent: :destroy

  
         has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
         has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
         
         has_many :following, through: :active_relationships, source: :followed
         has_many :followers, through: :passive_relationships, source: :follower
         
  action_store :like, :group , counter_cache: true
  action_store :like, :project , counter_cache: true
         # helper methods
         
         # follow another user
         def follow(other)
           active_relationships.create(followed_id: other.id)
         end
         
         # unfollow a user
         def unfollow(other)
           active_relationships.find_by(followed_id: other.id).destroy
         end
         
         # is following a user?
         def following?(other)
           following.include?(other)
         end
    #     has_many :active_relationships ,class_name: "Relationship", foreign_key: "follower_id" , dependent: :destroy
    #     has_many :passive_relationships , class_name: "Relationship" , foreign_key: "followed_id", dependent: :destroy
    #     has_many :following , through: :active_relationships , source: followed
    #     has_many :followers , through: :passive_relationships , source: follower


    #     def follow(other)
    #     	active_relationships.create(followed_id: other.id)
    #     end

    #     def unfollow(other)
    #     	active_relationships.find_by(followed_id: other.id).destroy
    #     end
    def name 
    	self.email.split('@')[0].capitalize
    end


     #    def following?(other)
      #   	following.include?(other)
       #  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end


  def profile

    if (User.find_by_username(params[:id]))
      @username = params[:id]
    else 
      # redirect to 404 (root for now)
      redirect_to root_path, :notice=> "User not found!" 
    end
    
    @posts = Post.all.where("user_id = ?", User.find_by_username(params[:id]).id)
    @newPost = Post.new
    
    @toFollow = User.all.last(5)
    
  end

  def welcome 

  end

  def explore
    @friends = current_user.following 
    @posts = Post.all.where("user_id = ?" , @friends.ids )


    @newPost = Post.new
    
    @toFollow = User.all.last(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/common/_footer.html.erb
<footer class="footer">
    <p class="lead">copyright@dormouse 2018.10.30</p>
  
</footer>

app/views/common/_navbar.html.erb
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
      <div class="navbar-brand">DorC</div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <%= link_to "Home", root_url,:class => "nav-link" %><span class="sr-only">(current)</span>
          </li>
          <a class="nav-link" href="/posts">Posts</a>



            <% if !current_user %>
              <li class="nav-item">
                <%= link_to "Login" ,new_user_session_url ,:class => "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Register" ,new_user_registration_path ,:class => "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle"  id="dropdown10" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.username %></a>
              <div class="dropdown-menu" aria-labelledby="dropdown07">
                <%= link_to "Show" ,user_path(current_user) ,:class=>"dropdown-item" %>
              <%= link_to "Edit" ,edit_user_registration_url(current_user) ,:class=>"dropdown-item" %>
               <%= link_to "Logout" ,destroy_user_session_path ,:class=>"dropdown-item",method: :delete %>
              </div>
            </li>
            <% end %>
          
         <% if current_user %>
          <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle"  id="dropdown10" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Explore</a>
             <div class="dropdown-menu" aria-labelledby="dropdown07"> 
                <a class="nav-link" href="/user/<%= current_user.username %>">Profile</a> 
                <a class="nav-link" href="/explore">Moments</a>
             </div>
          </li>
           <% end %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

app/views/layouts/_alert.html.erb
<p class="notice"><%=notice%></p>
<p class="alert"><%=alert%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Databases</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <%= render 'common/navbar' %>
    <%= render 'layouts/alert' %>


<% if params[:id] != nil %>
  <% @url = '/user/' + params[:id] %>
  <% if current_page?(@url) %>
    <img src="/banner.jpg" class="profile-banner">
    <div class="row">
      <div class="col-sm-12" style="background-color: white;">
        <div class="container">
            <div class="row">
              <div class="col-md-4" style="font-size: 100%; opacity: 0.7;">POSTS<br>
                      <h6 style="color: #0084B4; font-size: 150%;"><%= User.find_by_username(params[:id]).posts.count %></h6>
              </div>
              <div class="col-md-4" style="font-size: 100%; opacity: 0.7;">FOLLOWERS<br>
                      <h6 style="color: #0084B4; font-size: 150%;"><%= User.find_by_username(params[:id]).followers.count %></h6>
              </div>
              <% if current.username == params[:id] %>
              <div class="col-md-4" style="text-align: right; margin-top: 5px;"><a href="/users/edit"><li type="button" class="btn btn-default">EDIT PROFILE</li></a>
              </div>
              <%else%>
              <div class="col-md-4"></div>
              <% end %>
            </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

    <div class= "container">
        <%= yield %>
    </div>
  </body>
</html>

app/views/pages/explore.html.erb
<div class="row">
    <div class="col-md-3">
        
        <div class="panel panel-default">
          <div class="panel-body">
            <h5 style="color: grey; font-size: 125%;">Explore</h5>
            <p style="opacity: 0.5; font-size: 90%;">
              This page aggregates posts from ALL users. This means that you can find new people to follow,
              and your posts will also appear here so other people can see your opinions and interests and follow you
              if they chose.
            </p>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
             <h5 style="color: grey; font-size: 125%;">Trends</h5>
              <a href="">#Trend #1</a><br>
                <span style="color: grey;">31k Posts</span><br><br>
              <a href="">#Trend #2</a><br>
                <span style="color: grey;">25k Posts</span><br><br>
              <a href="">#Trend #3</a><br>
                <span style="color: grey;">16k Posts</span><br><br>
          </div>
        </div>
    </div>


    <div class="col-md-6">
        <%= render '/components/post_form' %><% if user_signed_in? %> <br> <% end %> <br>
        
        <% for @p in @posts %>
        <div class="panel panel-default post-panel">
          <div class="panel-body row">
            
            <div class="col-sm-1">
              <img src="/avatar.png" class="rounded-img" height="50px" width="50px"></img>
            </div>
            <div class="col-sm-11">
              <p class="post-title"><span class="post-owner"><a href="/user/<%= User.find(@p.user_id).username %>"><%= User.find(@p.user_id).username %></a></span> <span class="post-creation">- <%= @p.created_at.to_formatted_s(:short) %></span></p>
              <p class="post-content"><%= @p.body %></p>
            </div>
            
            <div class="col-sm-12">
              <p class="post-links">
                <span class="glyphicon glyphicon-comment g-links" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-retweet g-links" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-heart g-links" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-option-horizontal g-links" aria-hidden="true"></span>
                <center><a href="">View conversation</a></center>
              </p>
            </div>
            
          </div>
        </div>
        <% end %>
        
        <div class="panel panel-default post-panel">
          <div class="panel-body row">
            <div class="col-sm-12">
            <center><img src="/icon.png" height="25px" width="25px"></img>
              <a href="#top"><p class="opacity: .7;">Back to top <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span></p></a></center>
            </div>
          </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
          <div class="panel-body">
             <h5 style="color: grey; font-size: 125%;">Who to follow</h5>
             <% for @u in @toFollow do %>
               <p style="font-weight: bold; opacity: 0.85;" ><a href="/user/<%= @u.username %>"><%= @u.username %></a></p>
             <% end %>
          </div>
        </div>
        
        <div class="panel panel-default">
          <div class="panel-body">
            <p style="opacity: 0.5; font-size: 90%;">© 2018-2019 by: dormouse</p>
          </div>
        </div>
        
        
    </div>
</div>

app/views/pages/home.html.erb
<div class="row clearfix">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-12">
                <div class="jumbotron">
                    <h1 class="display-3">Welcome to Bangumi</h1>
                        <p>This is a simple sports social website .<br> Created by dormouse and haohao.</p>
                        <% if !current_user %>
                        <p class="lead">
                        <%= button_to "login" ,new_user_session_path,:class => "btn btn-primary btn-lg" %>
                        </p>
                        <% else %>
                         <%= button_to "logout" ,destroy_user_session_path,:class => "btn btn-primary btn-lg" ,method: :delete %>
                        <% end %>
                </div>
            </div>     
        </div>
        <div class="row">
            <div class="col-md-3">
                <div class="card" style="width: 18">
                    <img class="card-img-top" src="http://www.anicoga.com/wp-content/uploads/2018/07/2018071018413796.jpg" alt="Card image cap" style="height:200px">
                    <div class="card-body">
                        <h5 class="card-title"> Sakurajima Mai</h5>
                        <p class="card-text">Main heroine of "青春ブタ野郎はゆめみる少女の夢を見ない" ,the most famouse bangumi now </p>
                            <%= button_to "Groups" , groups_url , class: "btn btn-primary" ,method: :get %>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card" style="width: 18">
                    <img class="card-img-top" src="http://p0.qhimgs4.com/t013221d12d1e7b34e3.jpg" alt="Card image cap" style="height:200px">
                    <div class="card-body">
                        <h5 class="card-title">Totoro</h5>
                        <p class="card-text">Totoro is delighted at both the shelter and the sounds made upon it by falling raindrops.</p>
                           <%= button_to "Projects" , projects_url , class: "btn btn-primary" ,method: :get %>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card" style="width: 18 , height: 100 ">
                    <%= image_tag( "useless_welcome_3.jpg", :class =>"card-img-right flex-auto d-none d-md-block", :alt =>"Card image cap",:height => "200px") %>
                    <div class="card-body">
                        <h5 class="card-title">Megumi Kato</h5>
                        <p class="card-text">Megumi is Tomoya's classmate and the title character, who despite being good-looking </p>
                            <%= button_to "Categories" , categories_url , class: "btn btn-primary" ,method: :get %>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card" style="width: 18">
                    <%= image_tag( "useless_welcome_4.jpg", :class =>"card-img-right flex-auto d-none d-md-block", :alt =>"Card image cap",:height => "200px") %>
                    <div class="card-body">
                        <h5 class="card-title">Chiya Ujimatsu</h5>
                        <p class="card-text">Cocoa's classmate and friend at high school, whose family runs a coffee shop of their own</p>
                            <%= button_to "Places" , places_url , class: "btn btn-primary" ,method: :get %>
                    </div>
                </div>
            </div>    
        </div>
    </div>
</div>






















<!--



<% if current_user %>

<%= link_to 'Sign out' , destroy_user_session_path  , method:  :delete %>
<%= link_to 'Groups' ,groups_path %> 
<%else %>
<%= link_to 'Sign up' , new_user_registration_path %>
<%= link_to 'Sign in' , new_user_session_path %>
<% end %>


<%= link_to 'Posts' ,posts_path %> 

-->

app/views/pages/index.html.erb
<% if !current_user %>
	<style>
        body {
            background: linear-gradient( /* somewhat transparent film on top of the BG to make it look darker. */
                rgba(0,0,0, 0.7),
                rgba(0,0,0, 0.7)
                ), url("/bg.jpg") no-repeat center center fixed
            
            ; /* only display once, center horizontal and vertical, dont let scroll change position. */
            -webkit-background-size: cover;
            -moz-background-size: cover; /* cover the whole html element. */
            -o-background-size: cover;
            background-size: cover;
        }
        h1 {
            color: white;
            font-weight: bold;
        }
        .container-index {
            margin-right: 15%;
            margin-left: 15%;
        }
        .text {
            color: white;
            font-weight: 300;
            font-size: 150%;
        }
        .footer-links {
            text-align: center;
            color: white;
            margin-top: 30%;
            font-size: 75%;
        }
        .log-in {
            float: right;
            width: 300px;
            height: 150px;
            margin-top: 7.5%;
        }
        .sign-up {
            float: right;
            width: 300px;
            height: 250px;
        }
        .log-in-form {
            margin: 5px;
        }
    </style>
    
    <div class="container-index row">
        <div class="col-sm-6">
            <h1>Welcome to DorMouse.</h1>
            <p class="text">
                Connect with your buddies. Chat with new friends.<br>
                Share your adventures. Have fun! <br>
                Just like a blog, but with less characters!
            </p>
        </div>
        <div class="col-sm-6">
                   <div class="log-in panel">
                       Log In
                    </div> 
                    
                   <div class="sign-up panel">
                        Sign Up
                   </div> 
        </div>

    </div>

<% else # if the user IS signed in, render the following %>

    <script>document.location = "/home"</script>

<% end %>

app/views/pages/profile.html.erb
<!-- begin row 2. -->
<div class="row">
    <div class="col-md-3">

      <div class="col-sm-12">
        <h3 style="font-weight: bold;"><%= params[:id] %></h3>
        <p>
        </p>
      </div>
    </div>
    
    <div class="col-md-6">
      <% if current_user.username == params[:id] %>
        <%= render '/components/post_form' %><br><br>
       <%end %> 
        <% for @p in @posts %>
        <div class="panel panel-default post-panel">
          <div class="panel-body row">
            
            <div class="col-sm-1">
              <img src="/avatar.png" class="rounded-img" height="50px" width="50px"></img>
            </div>
            <div class="col-sm-11">
              <p class="post-title"><span class="post-owner"><a href="/user/<%= User.find(@p.user_id).username %>"><%= User.find(@p.user_id).username %></a></span> <span class="post-creation">- <%= @p.created_at.to_formatted_s(:short) %></span></p>
              <p class="post-content"><%= @p.body %></p>
            </div>
            
            <div class="col-sm-12">
              <p class="post-links">
                <span class="glyphicon glyphicon-comment g-links" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-retweet g-links" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-heart g-links" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-option-horizontal g-links" aria-hidden="true"></span>
                <center><%= link_to "show detail" , post_url(@p)  %></center>
              </p>
            </div>
            
          </div>
        </div>
        <% end %>
        
        <div class="panel panel-default post-panel">
          <div class="panel-body row">
            <div class="col-sm-12">
            <center><img src="/icon.png" height="25px" width="25px"></img>
              <a href="#top"><p class="opacity: .7;">Back to top <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span></p></a></center>
            </div>
          </div>
        </div>
    </div>
    
    <div class="col-md-3">
        <%= render '/components/follow_button', :user => User.find_by_username(params[:id]) %>
        <div class="panel panel-default">
          <div class="panel-body">
             <h5 style="color: grey; font-size: 125%;">Who to follow</h5>
             <% for @u in @toFollow do %>
               <p style="font-weight: bold; opacity: 0.85;" ><a href="/user/<%= @u.username %>"><%= @u.username %></a></p>
             <% end %>
          </div>
        </div>
        
        <div class="panel panel-default">
          <div class="panel-body">
             <h5 style="color: grey; font-size: 125%;">Trends</h5>
              <a href="">#Trend #1</a><br>
                <span style="color: grey;">31k Posts</span><br><br>
              <a href="">#Trend #2</a><br>
                <span style="color: grey;">25k Posts</span><br><br>
              <a href="">#Trend #3</a><br>
                <span style="color: grey;">16k Posts</span><br><br>
          </div>
        </div>
    </div>
</div>